import { db } from "./db";
import { investmentStrategies, passiveIncomeOpportunities } from "@shared/schema";

export async function seedInvestments() {
  console.log("Seeding investment strategies...");

  const strategies = [
    {
      name: "S&P 500 Index Funds",
      category: "stocks",
      subcategory: "index_funds",
      riskLevel: "moderate",
      expectedReturn: "10.00",
      historicalReturn: "10.26",
      minInvestment: "1.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Invest in the 500 largest US companies through a single fund. Historically returns ~10% annually over the long term.",
      pros: ["Highly diversified across sectors", "Low fees (0.03-0.20%)", "Simple to manage", "Strong historical performance", "Tracks overall market growth"],
      cons: ["Market volatility in short term", "No downside protection", "Returns not guaranteed", "Taxable dividends"],
      bestFor: ["Long-term investors (10+ years)", "Retirement savings", "Beginners seeking diversification", "Passive investors"],
      volatility: "medium",
      taxTreatment: "taxable",
      platformSuggestions: ["Vanguard (VOO)", "Fidelity (FXAIX)", "Schwab (SWPPX)", "iShares (IVV)"],
    },
    {
      name: "High-Yield Savings Account",
      category: "savings",
      subcategory: "cash_equivalents",
      riskLevel: "very_low",
      expectedReturn: "4.50",
      historicalReturn: "4.50",
      minInvestment: "0.01",
      timeHorizon: "short",
      liquidity: "high",
      description: "FDIC-insured savings accounts offering 4-5% APY. Perfect for emergency funds and short-term savings with zero risk.",
      pros: ["FDIC insured up to $250k", "No market risk", "Instant liquidity", "Predictable returns", "No fees"],
      cons: ["Returns barely beat inflation", "Rate can change", "Not ideal for long-term growth", "Lower than stock market returns"],
      bestFor: ["Emergency funds", "Short-term savings goals", "Risk-averse investors", "Parking cash temporarily"],
      volatility: "very_low",
      taxTreatment: "taxable",
      platformSuggestions: ["Marcus by Goldman Sachs", "Ally Bank", "American Express Personal Savings", "CIT Bank"],
    },
    {
      name: "Real Estate Investment Trusts (REITs)",
      category: "real_estate",
      subcategory: "reits",
      riskLevel: "moderate",
      expectedReturn: "9.50",
      historicalReturn: "11.80",
      minInvestment: "10.00",
      timeHorizon: "medium",
      liquidity: "high",
      description: "Own real estate without buying property. REITs own commercial buildings, apartments, data centers, etc. and pay 90% of income as dividends.",
      pros: ["High dividend yields (4-8%)", "Real estate exposure without property management", "Diversification from stocks", "Inflation hedge", "Liquid (trade like stocks)"],
      cons: ["Interest rate sensitive", "Not tax-efficient (dividends taxed as income)", "Market volatility", "No control over properties"],
      bestFor: ["Income-seeking investors", "Portfolio diversification", "Real estate exposure without buying property", "Dividend investors"],
      volatility: "medium",
      taxTreatment: "taxable",
      platformSuggestions: ["Vanguard Real Estate ETF (VNQ)", "Realty Income (O)", "Prologis (PLD)", "American Tower (AMT)"],
    },
    {
      name: "Treasury Bonds",
      category: "bonds",
      subcategory: "government_bonds",
      riskLevel: "very_low",
      expectedReturn: "4.60",
      historicalReturn: "5.20",
      minInvestment: "100.00",
      timeHorizon: "medium",
      liquidity: "medium",
      description: "US government bonds backed by the full faith and credit of the United States. Currently yielding 4.6-4.9% with zero default risk.",
      pros: ["Zero default risk", "Predictable income", "Safe haven in market crashes", "Tax advantages (state tax-free)", "Capital preservation"],
      cons: ["Lower returns than stocks", "Inflation risk", "Interest rate risk", "Opportunity cost vs stocks"],
      bestFor: ["Conservative investors", "Near-retirees", "Portfolio diversification", "Capital preservation"],
      volatility: "low",
      taxTreatment: "tax_advantaged",
      platformSuggestions: ["TreasuryDirect.gov", "Vanguard Total Bond Market (BND)", "iShares 20+ Year Treasury (TLT)"],
    },
    {
      name: "Bitcoin & Cryptocurrency",
      category: "crypto",
      subcategory: "cryptocurrency",
      riskLevel: "very_high",
      expectedReturn: "30.00",
      historicalReturn: "100.00",
      minInvestment: "1.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Digital currencies with high volatility but significant upside potential. Bitcoin up 36% YTD in 2025. Extremely risky but potentially transformative.",
      pros: ["High growth potential", "24/7 trading", "Inflation hedge (limited supply)", "Portfolio diversification", "Decentralized"],
      cons: ["Extreme volatility (-80% drawdowns possible)", "Regulatory uncertainty", "Security risks", "No intrinsic value", "Speculative"],
      bestFor: ["Risk-tolerant investors", "Long-term believers in crypto", "Small portfolio allocation (1-5%)", "Tech-savvy investors"],
      volatility: "very_high",
      taxTreatment: "taxable",
      platformSuggestions: ["Coinbase", "Kraken", "Binance.US", "Gemini"],
    },
    {
      name: "Dividend Growth Stocks",
      category: "stocks",
      subcategory: "dividend_stocks",
      riskLevel: "moderate",
      expectedReturn: "8.00",
      historicalReturn: "9.50",
      minInvestment: "10.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Established companies with track records of increasing dividends annually. Provides growing income stream plus capital appreciation.",
      pros: ["Growing passive income", "Less volatile than growth stocks", "Quality companies", "Dividend reinvestment compounds returns", "Tax-advantaged (qualified dividends)"],
      cons: ["Lower growth than tech stocks", "Dividend cuts during recessions", "Sector concentration (utilities, consumer staples)", "Still subject to market risk"],
      bestFor: ["Income investors", "Retirees", "Long-term wealth building", "Dividend reinvestors"],
      volatility: "medium",
      taxTreatment: "tax_advantaged",
      platformSuggestions: ["Vanguard Dividend Appreciation (VIG)", "Schwab US Dividend Equity (SCHD)", "Procter & Gamble (PG)", "Johnson & Johnson (JNJ)"],
    },
    {
      name: "Corporate Bonds (Investment Grade)",
      category: "bonds",
      subcategory: "corporate_bonds",
      riskLevel: "low",
      expectedReturn: "5.50",
      historicalReturn: "6.00",
      minInvestment: "1000.00",
      timeHorizon: "medium",
      liquidity: "medium",
      description: "Bonds issued by financially strong corporations rated BBB or higher. Higher yield than Treasuries with moderate additional risk.",
      pros: ["Higher yields than Treasuries", "Relatively safe (investment grade)", "Predictable income", "Portfolio diversification", "Lower volatility than stocks"],
      cons: ["Credit risk (companies can default)", "Interest rate risk", "Less liquid than stocks", "Call risk"],
      bestFor: ["Conservative income seekers", "Diversifying bond portfolio", "Retirees needing income", "Risk-averse investors"],
      volatility: "low",
      taxTreatment: "taxable",
      platformSuggestions: ["Vanguard Intermediate-Term Corporate Bond (VCIT)", "iShares iBoxx Investment Grade Corporate Bond (LQD)", "Fidelity"],
    },
    {
      name: "Gold & Precious Metals",
      category: "real_estate",
      subcategory: "commodities",
      riskLevel: "moderate",
      expectedReturn: "6.00",
      historicalReturn: "7.50",
      minInvestment: "50.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Physical gold, gold ETFs, or mining stocks. Traditional safe haven and inflation hedge with 3,000+ year track record.",
      pros: ["Inflation hedge", "Safe haven during crises", "Portfolio diversification", "No counterparty risk (physical)", "Global acceptance"],
      cons: ["No cash flow or dividends", "Storage costs (physical)", "Volatile short-term", "Opportunity cost vs stocks", "Doesn't compound"],
      bestFor: ["Inflation protection", "Crisis hedge (5-10% allocation)", "Long-term wealth preservation", "Diversification"],
      volatility: "medium",
      taxTreatment: "taxable",
      platformSuggestions: ["SPDR Gold Shares (GLD)", "iShares Gold Trust (IAU)", "Physical gold (APMEX, JM Bullion)", "Barrick Gold (GOLD)"],
    },
    {
      name: "Target-Date Retirement Funds",
      category: "stocks",
      subcategory: "target_date_funds",
      riskLevel: "moderate",
      expectedReturn: "7.50",
      historicalReturn: "8.00",
      minInvestment: "1.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "All-in-one funds that automatically rebalance from stocks to bonds as you near retirement. Perfect 'set and forget' option.",
      pros: ["Automatic rebalancing", "Age-appropriate risk adjustment", "Professionally managed", "Ultimate simplicity", "Diversified globally"],
      cons: ["Higher fees than basic index funds", "One-size-fits-all approach", "Can't customize allocation", "May be too conservative"],
      bestFor: ["Retirement savers", "401(k) investors", "Hands-off investors", "Beginners"],
      volatility: "medium",
      taxTreatment: "tax_deferred",
      platformSuggestions: ["Vanguard Target Retirement 2050 (VFIFX)", "Fidelity Freedom 2050 (FFFHX)", "Schwab Target 2050 (SWYMX)"],
    },
    {
      name: "Peer-to-Peer Lending",
      category: "bonds",
      subcategory: "alternative_credit",
      riskLevel: "high",
      expectedReturn: "7.00",
      historicalReturn: "5.50",
      minInvestment: "25.00",
      timeHorizon: "short",
      liquidity: "low",
      description: "Lend money directly to individuals or small businesses. Returns of 5-9% but with default risk and limited liquidity.",
      pros: ["Higher yields than bonds", "Diversification from traditional investments", "Help individuals/businesses", "Monthly income"],
      cons: ["High default risk", "Not liquid (3-5 year loans)", "Platform fees", "No FDIC insurance", "Economic downturn risk"],
      bestFor: ["Experienced investors seeking alternative income", "Diversification (small allocation)", "Risk-tolerant income seekers"],
      volatility: "medium",
      taxTreatment: "taxable",
      platformSuggestions: ["LendingClub", "Prosper", "Funding Circle", "Upstart"],
    },
    {
      name: "International Stocks (Developed Markets)",
      category: "stocks",
      subcategory: "international_equities",
      riskLevel: "moderate",
      expectedReturn: "8.50",
      historicalReturn: "7.80",
      minInvestment: "1.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Invest in companies outside the US in developed countries (Europe, Japan, Canada, Australia). Provides geographic diversification.",
      pros: ["Geographic diversification", "Currency diversification", "Access to global leaders", "Potentially undervalued vs US", "Dividend yields often higher"],
      cons: ["Currency risk", "Political risk", "Lower returns than US historically", "Higher fees", "Tax complexity"],
      bestFor: ["Long-term diversification", "Global exposure", "Reducing US concentration risk"],
      volatility: "medium",
      taxTreatment: "taxable",
      platformSuggestions: ["Vanguard FTSE Developed Markets (VEA)", "iShares MSCI EAFE (EFA)", "Schwab International Equity (SCHF)"],
    },
    {
      name: "Small-Cap Stocks",
      category: "stocks",
      subcategory: "small_cap_equities",
      riskLevel: "high",
      expectedReturn: "12.00",
      historicalReturn: "11.90",
      minInvestment: "10.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Smaller companies ($300M-$2B market cap) with higher growth potential but more volatility. Historically outperform large caps long-term.",
      pros: ["Higher growth potential", "Less analyst coverage (inefficiencies)", "Acquisition targets", "Domestic focused (less global risk)", "Tax-loss harvesting opportunities"],
      cons: ["Much higher volatility", "Less liquidity", "Higher business risk", "Economic sensitivity", "More bankruptcies"],
      bestFor: ["Long-term aggressive investors", "Younger investors", "Portfolio diversification", "Risk-tolerant investors"],
      volatility: "high",
      taxTreatment: "taxable",
      platformSuggestions: ["Vanguard Small-Cap ETF (VB)", "iShares Russell 2000 (IWM)", "Schwab US Small-Cap (SCHA)"],
    },
    {
      name: "Emerging Market Stocks",
      category: "stocks",
      subcategory: "emerging_markets",
      riskLevel: "very_high",
      expectedReturn: "10.00",
      historicalReturn: "6.50",
      minInvestment: "10.00",
      timeHorizon: "long",
      liquidity: "high",
      description: "Invest in developing countries (China, India, Brazil, etc.). Higher growth potential with significantly higher risk and volatility.",
      pros: ["High growth potential (younger demographics)", "Diversification", "Currency upside", "Rising middle class", "Undervalued"],
      cons: ["Extreme volatility", "Political instability", "Currency risk", "Accounting standards vary", "Liquidity issues", "Regulatory risk"],
      bestFor: ["Very long-term investors", "Aggressive portfolios", "Small allocation for diversification (5-10%)"],
      volatility: "very_high",
      taxTreatment: "taxable",
      platformSuggestions: ["Vanguard FTSE Emerging Markets (VWO)", "iShares MSCI Emerging Markets (EEM)", "Schwab Emerging Markets (SCHE)"],
    },
    {
      name: "Municipal Bonds (Tax-Free)",
      category: "bonds",
      subcategory: "municipal_bonds",
      riskLevel: "low",
      expectedReturn: "3.50",
      historicalReturn: "4.50",
      minInvestment: "5000.00",
      timeHorizon: "medium",
      liquidity: "medium",
      description: "Bonds issued by state/local governments. Interest is federal tax-free (and often state tax-free). Ideal for high earners.",
      pros: ["Federal tax-free income", "Often state tax-free too", "Low default rates", "Supports local communities", "Predictable income"],
      cons: ["Lower yields than taxable bonds", "Credit risk varies by issuer", "Less liquid", "High minimum investments", "Call risk"],
      bestFor: ["High-income earners (24%+ tax bracket)", "Tax-efficient income", "Conservative investors", "State residents (double tax-free)"],
      volatility: "low",
      taxTreatment: "tax_free",
      platformSuggestions: ["Vanguard Tax-Exempt Bond (VTEB)", "iShares National Muni Bond (MUB)", "Fidelity Tax-Free Bond (FTABX)"],
    },
    {
      name: "I Bonds (Series I Savings Bonds)",
      category: "bonds",
      subcategory: "savings_bonds",
      riskLevel: "very_low",
      expectedReturn: "4.00",
      historicalReturn: "3.50",
      minInvestment: "25.00",
      timeHorizon: "medium",
      liquidity: "low",
      description: "US government savings bonds with inflation-adjusted rates. Currently ~4% with zero default risk. Must hold 1 year minimum.",
      pros: ["100% inflation protected", "Zero default risk", "State/local tax-free", "Low minimum ($25)", "Backed by US government"],
      cons: ["$10k annual purchase limit", "Must hold 1 year minimum", "Penalty if sold before 5 years", "Lower returns than stocks", "Not liquid"],
      bestFor: ["Inflation protection", "Ultra-conservative savers", "Diversifying bond holdings", "Small allocations"],
      volatility: "very_low",
      taxTreatment: "tax_advantaged",
      platformSuggestions: ["TreasuryDirect.gov (only option)"],
    },
  ];

  await db.insert(investmentStrategies).values(strategies);
  console.log(`Seeded ${strategies.length} investment strategies`);

  console.log("Seeding passive income opportunities...");

  const passiveIncomes = [
    {
      name: "Digital Products (eBooks, Courses, Templates)",
      category: "digital_products",
      startupCost: "low",
      monthlyEarningsMin: "100.00",
      monthlyEarningsMax: "5000.00",
      effortLevel: "high",
      timeToProfit: "3_6_months",
      scalability: "high",
      description: "Create once, sell forever. Build eBooks, online courses, Notion templates, spreadsheets, or design assets. Earnings scale infinitely with no inventory costs.",
      requiredSkills: ["Writing/Design", "Marketing", "Subject matter expertise", "Basic tech skills"],
      platforms: ["Gumroad", "Teachable", "Udemy", "Etsy (digital)", "Amazon KDP"],
      pros: ["Zero marginal cost per sale", "Fully passive after creation", "Infinitely scalable", "Global audience", "No inventory"],
      cons: ["High upfront time investment", "Marketing required", "Competitive space", "Need audience/platform", "Income varies wildly"],
      bestFor: ["Experts in a field", "Creators/educators", "Designers", "Writers", "Anyone with teachable skills"],
    },
    {
      name: "Dividend Stocks Portfolio",
      category: "investments",
      startupCost: "medium",
      monthlyEarningsMin: "100.00",
      monthlyEarningsMax: "2000.00",
      effortLevel: "low",
      timeToProfit: "immediate",
      scalability: "high",
      description: "Build a portfolio of dividend-paying stocks. With $50k invested at 4% yield = $2,000/year passive income. Reinvest to compound.",
      requiredSkills: ["Basic investing knowledge", "Patience", "Discipline"],
      platforms: ["Vanguard", "Fidelity", "Schwab", "Robinhood", "M1 Finance"],
      pros: ["Truly passive", "Compounds over time", "Tax-advantaged (qualified dividends)", "Growing income", "Capital appreciation too"],
      cons: ["Requires capital ($10k+ for meaningful income)", "Market risk", "Dividends can be cut", "Slow to build"],
      bestFor: ["Long-term investors", "Those with capital to invest", "Patient builders", "Retirement planning"],
    },
    {
      name: "YouTube Ad Revenue",
      category: "content_creation",
      startupCost: "very_low",
      monthlyEarningsMin: "100.00",
      monthlyEarningsMax: "5000.00",
      effortLevel: "very_high",
      timeToProfit: "6_12_months",
      scalability: "high",
      description: "Create evergreen video content that generates ad revenue for years. 1,000 subscribers + 4,000 watch hours to monetize. $2-7 per 1,000 views typical.",
      requiredSkills: ["Video editing", "Speaking/presentation", "SEO optimization", "Consistency"],
      platforms: ["YouTube", "AdSense"],
      pros: ["Videos earn for years", "Highly scalable", "Multiple revenue streams (ads, sponsors, affiliates)", "Build an audience", "Low startup cost"],
      cons: ["Extremely time-intensive upfront", "Slow to monetize", "Algorithm dependency", "High competition", "Burnout risk"],
      bestFor: ["Video creators", "Educators", "Entertainers", "Patient builders", "Those with unique expertise"],
    },
    {
      name: "Affiliate Marketing Blog/Website",
      category: "content_creation",
      startupCost: "low",
      monthlyEarningsMin: "200.00",
      monthlyEarningsMax: "3000.00",
      effortLevel: "high",
      timeToProfit: "6_12_months",
      scalability: "high",
      description: "Build a niche website with product reviews/comparisons. Earn commissions when visitors buy through your affiliate links. SEO-driven traffic.",
      requiredSkills: ["SEO", "Writing", "Web basics", "Marketing", "Niche research"],
      platforms: ["Amazon Associates", "ShareASale", "CJ Affiliate", "ClickBank", "WordPress"],
      pros: ["Evergreen content earns for years", "No product creation", "Multiple affiliate programs", "Scale with more content", "Passive once ranked"],
      cons: ["SEO takes 6-12 months", "Google algorithm changes", "Affiliate commission cuts", "Competitive niches", "Requires consistent content"],
      bestFor: ["Writers", "SEO enthusiasts", "Patient marketers", "Niche experts"],
    },
    {
      name: "Print on Demand (Merch, T-Shirts, Art)",
      category: "digital_products",
      startupCost: "very_low",
      monthlyEarningsMin: "100.00",
      monthlyEarningsMax: "2000.00",
      effortLevel: "medium",
      timeToProfit: "1_3_months",
      scalability: "high",
      description: "Design t-shirts, mugs, phone cases, etc. Third-party handles printing/shipping. You earn royalties per sale. Zero inventory risk.",
      requiredSkills: ["Graphic design", "Niche research", "Marketing basics"],
      platforms: ["Merch by Amazon", "Redbubble", "Printful", "Teespring", "Etsy"],
      pros: ["Zero inventory/shipping", "Fully automated fulfillment", "Global sales", "One design sells indefinitely", "Low startup cost"],
      cons: ["Low profit margins ($2-5/sale)", "Saturated market", "Design theft risk", "Platform dependency", "Need volume for income"],
      bestFor: ["Graphic designers", "Artists", "Trend spotters", "Side hustlers"],
    },
    {
      name: "Rental Income (Airbnb, Extra Room)",
      category: "real_estate",
      startupCost: "low",
      monthlyEarningsMin: "500.00",
      monthlyEarningsMax: "3000.00",
      effortLevel: "medium",
      timeToProfit: "immediate",
      scalability: "medium",
      description: "Rent out a spare room, basement, or property on Airbnb/VRBO. Earn $500-3,000/month depending on location. Semi-passive with property manager.",
      requiredSkills: ["Hospitality", "Property management basics", "Communication"],
      platforms: ["Airbnb", "VRBO", "Furnished Finder"],
      pros: ["Immediate income", "High earnings potential", "Leverage existing property", "Tax deductions", "Flexible hosting"],
      cons: ["Guest management time", "Property wear and tear", "Regulatory issues", "Not fully passive", "Income varies seasonally"],
      bestFor: ["Homeowners with extra space", "High-traffic location residents", "People-oriented hosts"],
    },
    {
      name: "High-Yield Savings/CDs Interest",
      category: "investments",
      startupCost: "medium",
      monthlyEarningsMin: "100.00",
      monthlyEarningsMax: "1000.00",
      effortLevel: "very_low",
      timeToProfit: "immediate",
      scalability: "medium",
      description: "Park emergency fund in 4-5% high-yield savings accounts or CDs. $25k at 5% = $1,250/year. Completely passive and FDIC insured.",
      requiredSkills: ["None - just open account"],
      platforms: ["Marcus", "Ally Bank", "American Express Savings", "CIT Bank"],
      pros: ["Zero risk (FDIC insured)", "Zero effort", "Instant liquidity", "Predictable returns", "No fees"],
      cons: ["Requires significant capital", "Returns barely beat inflation", "Not wealth-building", "Rate can change"],
      bestFor: ["Emergency funds", "Risk-averse savers", "Short-term parking", "Capital preservation"],
    },
    {
      name: "Stock Photography/Video",
      category: "digital_products",
      startupCost: "low",
      monthlyEarningsMin: "50.00",
      monthlyEarningsMax: "1000.00",
      effortLevel: "medium",
      timeToProfit: "3_6_months",
      scalability: "high",
      description: "Upload photos/videos to stock sites. Earn royalties every time someone downloads. One photo can sell hundreds of times over years.",
      requiredSkills: ["Photography/videography", "Editing", "Understanding market demand"],
      platforms: ["Shutterstock", "Adobe Stock", "iStock", "Getty Images", "Pond5 (video)"],
      pros: ["One asset sells infinitely", "Fully passive after upload", "Global marketplace", "Compound portfolio value", "Low startup cost"],
      cons: ["Extremely low per-sale royalty ($0.25-$5)", "Highly competitive", "Need large portfolio (500+)", "Trends change", "Time to build portfolio"],
      bestFor: ["Photographers", "Videographers", "Travelers", "Drone operators"],
    },
    {
      name: "License Music/Beats (Royalty Income)",
      category: "digital_products",
      startupCost: "low",
      monthlyEarningsMin: "100.00",
      monthlyEarningsMax: "2000.00",
      effortLevel: "high",
      timeToProfit: "3_6_months",
      scalability: "high",
      description: "Create instrumental beats, background music, or sound effects. License to YouTubers, filmmakers, podcasters. Earn royalties per use.",
      requiredSkills: ["Music production", "Audio engineering", "Genre knowledge"],
      platforms: ["BeatStars", "Soundstripe", "AudioJungle", "Epidemic Sound", "Artlist"],
      pros: ["One track earns indefinitely", "High demand (content creator boom)", "Multiple licensing models", "Portfolio compounds", "Creative work"],
      cons: ["Competitive field", "Requires music production skills/equipment", "Building library takes time", "Income inconsistent initially"],
      bestFor: ["Music producers", "Composers", "Beat makers", "Sound designers"],
    },
    {
      name: "Automated Dropshipping Store",
      category: "digital_products",
      startupCost: "medium",
      monthlyEarningsMin: "200.00",
      monthlyEarningsMax: "5000.00",
      effortLevel: "high",
      timeToProfit: "3_6_months",
      scalability: "very_high",
      description: "Sell products online without holding inventory. Supplier ships directly to customer. Automate with tools. Can be 80% passive once optimized.",
      requiredSkills: ["E-commerce", "Marketing", "Customer service", "Product research"],
      platforms: ["Shopify + Oberlo", "AutoDS", "Spocket", "AliExpress"],
      pros: ["No inventory costs", "Highly scalable", "Work from anywhere", "Automated fulfillment", "Multiple niches"],
      cons: ["Thin profit margins (10-20%)", "Shipping delays", "Customer service issues", "High competition", "Ad costs", "Not truly passive"],
      bestFor: ["Entrepreneurs", "Marketers", "E-commerce enthusiasts", "Risk-tolerant hustlers"],
    },
    {
      name: "App/Software SaaS Subscriptions",
      category: "digital_products",
      startupCost: "high",
      monthlyEarningsMin: "500.00",
      monthlyEarningsMax: "10000.00",
      effortLevel: "very_high",
      timeToProfit: "12_plus_months",
      scalability: "very_high",
      description: "Build a software product once, collect recurring monthly subscriptions forever. Holy grail of passive income but requires technical skills.",
      requiredSkills: ["Programming", "Product design", "Marketing", "Customer support"],
      platforms: ["Web app (self-hosted)", "Mobile app stores", "Chrome extensions"],
      pros: ["Recurring revenue (MRR)", "Infinitely scalable", "High profit margins", "Valuable asset (acquisition potential)", "True passive potential"],
      cons: ["Requires significant development time", "Technical expertise required", "Ongoing maintenance", "Competitive market", "Slow initial growth"],
      bestFor: ["Developers", "Product builders", "SaaS entrepreneurs", "Technical founders"],
    },
  ];

  await db.insert(passiveIncomeOpportunities).values(passiveIncomes);
  console.log(`Seeded ${passiveIncomes.length} passive income opportunities`);

  console.log("Investment seeding complete");
}
